import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { compose, dockerAvailable, repoRoot } from "./lib/docker.ts";

const schemaPath = join(repoRoot, "db", "schema.sql");
const write = process.argv.includes("--write");
const HEADER = "-- Generated by `just db::dump` (pg_dump --schema-only in the compose container). Do not edit.\n";

/** Remove nondeterministic lines (pg_dump 17.6+ \restrict keys, version banners). */
export function normalize(dump: string): string {
  const lines = dump
    .replace(/\r\n/g, "\n")
    .split("\n")
    .filter((line) => !/^\\(un)?restrict\b/.test(line) && !/^-- Dumped (from|by)\b/.test(line));
  return `${HEADER}${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`;
}

const ready = dockerAvailable()
  ? compose(["exec", "-T", "postgres", "pg_isready", "-U", "brain", "-d", "ai_second_brain"])
  : undefined;
if (ready === undefined || ready.status !== 0) {
  console.log("schema-check: SKIPPED (no database)");
  process.exit(0);
}

const dump = compose([
  "exec", "-T", "postgres", "pg_dump", "--schema-only", "--no-owner", "--no-privileges",
  "--exclude-table=public.schema_migrations", "-U", "brain", "ai_second_brain",
]);
if (dump.status !== 0) {
  console.error(dump.stderr);
  process.exit(1);
}
const fresh = normalize(dump.stdout);

if (write) {
  writeFileSync(schemaPath, fresh, "utf8");
  console.log("db/schema.sql written.");
  process.exit(0);
}

let committed = "";
try {
  committed = readFileSync(schemaPath, "utf8").replace(/\r\n/g, "\n");
} catch {
  committed = "";
}
if (committed !== fresh) {
  console.error("db/schema.sql is out of date. Run `just db::dump` and commit it.");
  process.exit(1);
}
console.log("schema-check: OK");
