/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAskRouteImport } from './routes/_app/ask'
import { Route as AppDigestRouteImport } from './routes/_app/digest'
import { Route as AppNodesRouteImport } from './routes/_app/nodes'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppAskIndexRouteImport } from './routes/_app/ask.index'
import { Route as AppAskSessionIdRouteImport } from './routes/_app/ask.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestRoute = AppDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesRoute = AppNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppAskIndexRoute = AppAskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAskRoute,
} as any)
const AppAskSessionIdRoute = AppAskSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AppAskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ask': typeof AppAskRouteWithChildren
  '/digest': typeof AppDigestRoute
  '/nodes': typeof AppNodesRoute
  '/projects': typeof AppProjectsRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/ask/$sessionId': typeof AppAskSessionIdRoute
  '/ask/': typeof AppAskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/digest': typeof AppDigestRoute
  '/nodes': typeof AppNodesRoute
  '/projects': typeof AppProjectsRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/ask/$sessionId': typeof AppAskSessionIdRoute
  '/ask': typeof AppAskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ask': typeof AppAskRouteWithChildren
  '/_app/digest': typeof AppDigestRoute
  '/_app/nodes': typeof AppNodesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/ask/$sessionId': typeof AppAskSessionIdRoute
  '/_app/ask/': typeof AppAskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ask'
    | '/digest'
    | '/nodes'
    | '/projects'
    | '/review'
    | '/search'
    | '/settings'
    | '/sources'
    | '/ask/$sessionId'
    | '/ask/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/digest'
    | '/nodes'
    | '/projects'
    | '/review'
    | '/search'
    | '/settings'
    | '/sources'
    | '/ask/$sessionId'
    | '/ask'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ask'
    | '/_app/digest'
    | '/_app/nodes'
    | '/_app/projects'
    | '/_app/review'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/ask/$sessionId'
    | '/_app/ask/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digest': {
      id: '/_app/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AppDigestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes': {
      id: '/_app/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AppNodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask/': {
      id: '/_app/ask/'
      path: '/'
      fullPath: '/ask/'
      preLoaderRoute: typeof AppAskIndexRouteImport
      parentRoute: typeof AppAskRoute
    }
    '/_app/ask/$sessionId': {
      id: '/_app/ask/$sessionId'
      path: '/$sessionId'
      fullPath: '/ask/$sessionId'
      preLoaderRoute: typeof AppAskSessionIdRouteImport
      parentRoute: typeof AppAskRoute
    }
  }
}

interface AppAskRouteChildren {
  AppAskSessionIdRoute: typeof AppAskSessionIdRoute
  AppAskIndexRoute: typeof AppAskIndexRoute
}

const AppAskRouteChildren: AppAskRouteChildren = {
  AppAskSessionIdRoute: AppAskSessionIdRoute,
  AppAskIndexRoute: AppAskIndexRoute,
}

const AppAskRouteWithChildren =
  AppAskRoute._addFileChildren(AppAskRouteChildren)

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRouteWithChildren
  AppDigestRoute: typeof AppDigestRoute
  AppNodesRoute: typeof AppNodesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRouteWithChildren,
  AppDigestRoute: AppDigestRoute,
  AppNodesRoute: AppNodesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
